services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5090:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build: ./services/postgres-rum
    volumes:
      # Volume for persistent data
      - postgres_data:/var/lib/postgresql/data/
      # Mount schema.sql to initialize the database
      - ./services/postgres-rum/schema.sql:/docker-entrypoint-initdb.d/01.sql:ro
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
